name: "Datasource handling"
stages:
  rootfs.before:
    - &datasource
      name: "Pull data from provider"
      datasource:
        providers: ["cdrom", "gcp", "openstack", "aws", "azure", "hetzner", "packet", "scaleway", "vultr", "digitalocean", "metaldata" ]
        path: "/oem"
    - if: '[ ! -f /oem/userdata ]'
      files:
      - path: /oem/userdata_load
  network:
    - <<: *datasource
    - if: '[ -f /oem/userdata ] && [ -f /oem/userdata_load ]'
      commands:
      - elemental cloud-init -s initramfs /oem/userdata
      - elemental cloud-init -s boot /oem/userdata
      - rm -rf /oem/userdata_load
