name: "Branding"
stages:
   initramfs:
     - name: "Branding"
       hostname: "c3os"
     - name: "Default systemd config"
       if: '[ -e "/sbin/systemctl" ] || [ -e "/usr/bin/systemctl" ] || [ -e "/usr/sbin/systemctl" ] || [ -e "/usr/bin/systemctl" ]'
       systemd:
        enable:
        - multi-user.target
        - getty@tty1
        - iscsid
        - systemd-timesyncd
        mask:
        - purge-kernels
       commands:
       - systemctl set-default multi-user.target
