name: "Setup default network"
stages:
   initramfs:
    - name: "Setup network"
      files:
      - path: /etc/sysconfig/network/ifcfg-eth0
        content: |
                BOOTPROTO='dhcp'
                STARTMODE='onboot'
        permissions: 0600
        owner: 0
        group: 0
    - systemctl:
        enable:
        - wicked

