name: "Additional grub menu entries"
stages:
    # TODO: anchor to after-reset, after-upgrade
    after-install:
    - name: "Mount state"
      commands:
      - |
          STATEDIR=/tmp/mnt/STATE
          STATE=$(blkid -L COS_STATE || true)
          mkdir -p $STATEDIR || true
          mount ${STATE} $STATEDIR
    - name: "Add grubmenu"
      files:
       # TODO: boot assessment is part of grubmenu, should be a separate file
       - path: "/tmp/mnt/STATE/grubmenu"
         owner: 0
         group: 0
         permsisions: 0600
         content: |
            menuentry "c3os remote recovery" --id remoterecovery {
              if search.file /cOS/recovery.squashfs ; then
                set img=/cOS/recovery.squashfs
                set recoverylabel=COS_RECOVERY
              else
                set img=/cOS/recovery.img
              fi
              search.fs_label COS_RECOVERY root
              set label=COS_SYSTEM
              loopback loop0 /$img
              set root=($root)
              source (loop0)/etc/cos/bootargs.cfg
              linux (loop0)$kernel $kernelcmd ${extra_cmdline} ${extra_recovery_cmdline} vga=795 nomodeset c3os.remote_recovery_mode
              initrd (loop0)$initramfs
            }

            set extra_active_cmdline="rd.emergency=reboot rd.shell=0 panic=5"
            set custom="/c3osenv"
            search --no-floppy --file --set=custom_blk "${custom}"
            if [ "${custom_blk}" ]; then
              load_env -f "(${custom_blk})${custom}"
            fi
            set customgrub="/c3osgrub"
            search --no-floppy --file --set=custom_grub_blk "${customgrub}"
            if [ "${custom_grub_blk}" ]; then
              source "(${custom_grub_blk})${customgrub}"
            fi
    - name: "umount state"
      commands:
      - |
          umount /tmp/mnt/STATE